application: goherenext
version: 1
runtime: python27
threadsafe: true
api_version: 1

builtins:
- appstats: on

handlers:

- url: /favicon.ico
  static_files: favicon.ico
  upload: favicon.ico

- url: /css
  static_dir: css

- url: /pages
  static_dir: pages

- url: /admin
  static_dir: admin
  login: required
  
- url: /js
  static_dir: js

- url: /images/(.*\.(gif|jpg|png))
  static_files: images/\1
  upload: images/(.*\.(gif|jpg|png))
  expiration: 5h

- url: /rpc
  script: app.application

- url: /rpcedit
  script: app.application
  login: required
  
- url: /.*
  script: app.application
